export const ActionTypes = {
    SET_USERS: 'SET_USERS',
    SELECTED_USER: 'SELECTED_USER',
    REMOVE_SELCTED_USER: 'REMOVE_SELCTED_USER',
    SET_LOGIN_STATUS: 'SET_LOGIN_STATUS',
    SET_LOGOUT_STATUS: 'SET_LOGOUT_STATUS',

};